version: '2'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "127.0.0.1:27017:27017"
  server:
    image: eduboard/backend:latest
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      STATIC_DIR: "/var/www/static/"
    links:
      - mongo:mongo
    volumes:
      - ./static:/var/www/static
