version: '2'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "127.0.0.1:27017:27017"
  server:
    image: eduboard/backend:latest
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://mongo:27017"
    links:
      - mongo:mongo
